# Numpy

수치해석용 파이썬 패키지
list에 담긴 데이터를 matrix로 만들어 관리할 때 사용

- 행렬 안에 있는 모든 값은 동일한 타입
- 관리하는 원소의 개수를 변경할 수 없다

### package import

In [1]:
import numpy as np

### 1차원 배열만들기 (행렬 = 배열)

In [3]:
list1 =[10, 20, 30, 40, 50]
array1 =np.array([10, 20, 30, 40, 50])

print(list1)
print(array1)

print(type(list1))
print(type(array1))

[10, 20, 30, 40, 50]
[10 20 30 40 50]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
array1

array([10, 20, 30, 40, 50])

In [5]:
print(array1)

[10 20 30 40 50]


### 벡터 연산


In [6]:
print(list1 * 3)
print(array1 * 3)

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[ 30  60  90 120 150]


In [7]:
print(array1)
print(array1 + 10)
print(array1 - 10)
print(array1 * 10)
print(array1 // 10)

[10 20 30 40 50]
[20 30 40 50 60]
[ 0 10 20 30 40]
[100 200 300 400 500]
[1 2 3 4 5]


list2 = [10, 20, 30, 40, 50]
list3 = [1, 2, 3, 4, 5]
print(list2 + list3)

In [8]:
array2 = np.array([10, 20, 30, 40, 50])
array3 = np.array([1, 2, 3 ,4, 5])
print(array2 + array3)

[11 22 33 44 55]


In [9]:
print(array2 == 30)

[False False  True False False]


첫번째 값 끄집어내서 계산해보고 두번째 값 끄집어내서 계산해보고 세번째 값 끄집어내서 계산해보고 네번째값 끄집어내서 계산해보고 ...
관리하는 값들을 하나씩 하나씩 

### 2차원 배열 만들기

In [12]:
list1 = [
    [1, 2, 3], 
    [4, 5, 6]
]
list1

[[1, 2, 3], [4, 5, 6]]

In [14]:
array1 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 행의 개수
len(array1)

2

In [16]:
# 열의 개수
len(array1[0])

3

### 다양한 타입

행렬은 다양한 타입의 값을 담을 수 없다.

행렬을 생성할 때 다양한 타입을 넣어주면 해당 타입을 모두 표현이 가능한 형태로 표현된다.

In [20]:
list1 = [10, 11.11, True, '안녕']
array1 = np.array([10, 11.11, True, '안녕'])
print(list1)
print(array1)

[10, 11.11, True, '안녕']
['10' '11.11' 'True' '안녕']


In [21]:
# 0으로 채워진 행열을 생선한다.
array2 = np.zeros(5)
array2

array([0., 0., 0., 0., 0.])

In [24]:
array3 = np.zeros([2, 3], dtype='i')
array3

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [25]:
array5 = np.ones([2, 3], dtype='i')
array5

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [26]:
#쓰레기 값이 담긴 행렬 생성
array6 = np.empty([2, 3])
array6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# 특정 범위 값을 가지고 있는 행렬 생성
# 0 ~ 10-1
array7 = np.arange(10)
print(array7)

# 3 ~ 12 -1 
array8 = np.arange(3, 12)
print(array8)

# 3 ~ 12 -1 , 2씩 증가
array9 = np.arange(3, 12, 2)
print(array9)

[0 1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10 11]
[ 3  5  7  9 11]


In [31]:
# 특정 범위 안에서 원하는 만큼의 숫자를 추출해 행열로 생성한다.
# 시작값, 끝값, 배수
array10 = np.linspace(0, 100, 5)
print(array10)

[  0.  25.  50.  75. 100.]


### 전치연산(행열바꾸기)

In [34]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = array1.T

print(array1)
print(array2)

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


### 배열의 크기 변형

In [35]:
array1 = np.arange(12)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
# 배열을 3행 4열 행렬로 만든다.
array2 = array1.reshape(3, 4)
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
# 행열을 배열로 만든다.
array3 = array2.flatten()
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])