In [6]:
import numpy as np

In [9]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
print(f'차원 수 : {array1.ndim}')
print(f'행열 수 : {array1.shape}')
print(f'차원 수 : {array2.ndim}')
print(f'행열 수 : {array2.shape}')

차원 수 : 1
행열 수 : (3,)
차원 수 : 2
행열 수 : (2, 3)


### 배열의 인덱싱

In [12]:
list1 = [10, 20, 30, 40, 50,]
list2 = [[10, 20, 30], [40, 50, 60]]
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([[10, 20, 30], [40, 50, 60]])

In [14]:
# 0번째(첫번째) 값을 가지고 온다.
print(list1[0])
print(array1[0])
# 2번째(세번째) 값을 가지고 온다.
print(list1[2])
print(array1[2])
# -1번째 값을 가지고 온다.
print(list1[-1])
print(array1[-1])
# -3번째 값을 가지고 온다.
print(list1[-3])
print(array1[-3])

10
10
30
30
50
50
30
30


In [17]:
# 0행 0열 값을 가져온다.
print(list2[0][0])
print(array2[0, 0])
# 1행 2열 값을 가져온다
print(list2[1][2])
print(array2[1, 2])
#마지막행 마지막열 값을 가져온다.
print(list2[-1][-1])
print(array2[-1][-1])

10
10
60
60
60
60


In [19]:
# True, False를 이용한 값 가져오기.
# [] 안에 True와 False가 담긴 행렬을 넣어주면 True 자리에 해당하는 값만 가져온다.
array3 = np.array([True, False, True, False, True])
print(array1[array3])

[10 30 50]


In [23]:
array4 = np.array([[True, False, True], [True, False, True]])
print(array2[array4])


[10 30 40 60]


In [32]:
#array1에서 20보다 큰 값만 가져온다.

print(array1)
print(array1 > 20)
print(array1[array1>20])

# 안에 조건을 넣는게 아니라, 행렬을 자리에 집어 넣는 것

[10 20 30 40 50]
[False False  True  True  True]
[30 40 50]


In [30]:
# array1에서 20의 배수만 가져온다.

#전체를 가져온다.

print(array1)

#20의 배수인지 확인한다.
print(array1 % 20)

[10 20 30 40 50]
[10  0 10  0 10]


## 배열 슬라이싱

In [34]:
list1 = [10, 20, 30, 40, 50]
lits2 = [
    [10, 20, 30], 
    [40, 50, 60]
]

array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([
    [10, 20, 30], 
    [40, 50, 60]
])

In [35]:
# 일부만 가져온다.
# 시작인덱스 : 끝인덱스 -1

print(list1[1:4])
print(list2[0:1][0:1])

[20, 30, 40]
[[10, 20, 30]]


In [36]:
print(array1[1:4])

[20 30 40]


In [37]:
# 처음부터 3 -1 까지
print(array1[:3])
# 1 ~ 끝까지
print(array1[1:])


[10 20 30]
[20 30 40 50]


In [43]:
array3 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

In [44]:
# 1~ 4-1 행, 1~ 4-1 열
print(array3[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [45]:
# 0 ~ 4-1 행, 1 ~ 끝열
print(array3[:4, 1:])

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]


In [50]:
# 1행, 모든 열
print(array3[1])

# 1 ~ 4-1행, 모든 열
print(array3[1:4])

# ahemsgod, 3번째열 전체
print(array3[:, 2])

# 2번째열 전체
print(array3[1, :])

[ 6  7  8  9 10]
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 3  8 13 18 23]
[ 6  7  8  9 10]
